// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';

class ColorTokens {
  static const Color textPrimary = Color(0xFF2C3441);
  static const Color textSecondary = Color(0xFF797F89);
  static const Color textSecondarylight = Color(0xFFA9ACB1);
  static const Color neutralBackground = Color(0xFF1F1E24);
  static const Color neutralBorder = Color(0xFFE5E5E5);
  static const Color neutralLight = Color(0xFFFFFFFF);
  static const Color neutralLightBackground = Color(0xFFF7F7F7);
  static const Color accentPurple = Color(0xFF916CFF);
  static const Color accentPurpleAlpha = Color(0x1A916CFF);
  static const Color accentBlue = Color(0xFF0090FF);
  static const Color accentBlueAlpha = Color(0x1A0090FF);
  static const Color accentRed = Color(0xFFFF002B);
  static const Color accentRedAlpha = Color(0x1AFF002B);
  static const Color accentYellow = Color(0xFFF1B900);
  static const Color accentYellowAlpha = Color(0x1AF1B900);
  static const Color accentGreen = Color(0xFF13A700);
  static const Color accentGreenAlpha = Color(0x1A13A700);
  static const Color accentBlueText = Color(0xFF809FB8);
  static const Color accentPurpleText = Color(0xFF9C80B8);
  static const Color accentGreenText = Color(0xFF97B880);

  static const LinearGradient gradientDark = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0xFF303030), Color(0xFF1C1C1C)],
  );
  static const LinearGradient gradientPurple = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0xCC916CFF), Color(0x03916CFF)],
  );
  static const LinearGradient gradientBlue = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0xCC0090FF), Color(0x030090FF)],
  );
}
