// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';

class ElevationTokens {
  static const BoxShadow e1 = BoxShadow(
    color: Color(0x43FFFFFF),
    offset: Offset(0.0, 5.0),
    blurRadius: 5.0,
  );
}
