// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TypographyTokens {
  static TextStyle bodyXxsmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 12.0.sp,
    fontWeight: FontWeight.w100,
  );
  static TextStyle bodyXsmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 14.0.sp,
    fontWeight: FontWeight.w100,
  );
  static TextStyle bodySmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w100,
  );
  static TextStyle bodyMedium = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 20.0.sp,
    fontWeight: FontWeight.w400,
  );
  static TextStyle bodyLarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 24.0.sp,
    fontWeight: FontWeight.w400,
  );
  static TextStyle bodyXlarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 28.0.sp,
    fontWeight: FontWeight.w400,
  );
  static TextStyle bodyXxlarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 32.0.sp,
    fontWeight: FontWeight.w400,
  );
  //heading
  static TextStyle headingXxsmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 12.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle headingXsmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 14.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle headingSmall = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle headingMedium = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 20.0.sp,
    fontWeight: FontWeight.w900,
  );
  static TextStyle headingLarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 24.0.sp,
    fontWeight: FontWeight.w900,
  );
  static TextStyle headingXlarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 28.0.sp,
    fontWeight: FontWeight.w900,
  );
  static TextStyle headingXxlarge = TextStyle(
    fontFamily: 'Circular Std',
    fontSize: 32.0.sp,
    fontWeight: FontWeight.w900,
  );
}
