name: Generate Flutter Design Tokens

on:
  push:
    branches:
      - token
    paths:
      - "tokens/tokens.json"

permissions:
  contents: write

jobs:
  generate_tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Run token generator
        run: dart run tool/token_generator.dart

      - name: Format generated files
        run: dart format .

      - name: Analyze generated files
        run: flutter analyze --fatal-infos .

      - name: Commit and push generated tokens
        run: |
          git config user.name "miny-bot"
          git config user.email "bot@miny.dev"
          git add lib/src/tokens/
          git add lib/src/theme/extensions/
          git diff --cached --quiet || git commit -m "chore: regenerate & format tokens"
          git push
